### ISSUE TITLE
How top open a Second Window?

### ISSUE THREAD

**Issue by ghost** [blunty666/Tiles#3]
How top open a Second Window?

**Comment by blunty666** [comment]
Do you mean in the multiglass program?

To do that just double right click in any clear area when using the wireless keyboard.

**Comment by ghost** [comment]
Thx and Planning on adding new Features ?

**Comment by ghost** [comment]
How can i close a Extra terminal ?

**Comment by blunty666** [comment]
Hadn't got any new features in mind, but being able to close windows directly might have to be one.

At the moment you have to click and hold the "T" button a few times until the top shell for that window exits, so an extra button that just closes the window might be a good idea.

**Comment by blunty666** [comment]
I've updated multiglass now to add a button to windows that closes them. Just click and hold for half a second, then release and the window will close.
